## **Import Libraries**

In [1]:
import numpy as np
import tensorflow as tf


## **Open Text Dataset**

In [2]:
with open("/content/1661-0.txt", "r", encoding="utf-8") as file:
  text = file.read()

In [3]:
text

'\ufeff\nProject Gutenberg\'s The Adventures of Sherlock Holmes, by Arthur Conan Doyle\n\nThis eBook is for the use of anyone anywhere at no cost and with\nalmost no restrictions whatsoever.  You may copy it, give it away or\nre-use it under the terms of the Project Gutenberg License included\nwith this eBook or online at www.gutenberg.net\n\n\nTitle: The Adventures of Sherlock Holmes\n\nAuthor: Arthur Conan Doyle\n\nRelease Date: November 29, 2002 [EBook #1661]\nLast Updated: May 20, 2019\n\nLanguage: English\n\nCharacter set encoding: UTF-8\n\n*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF SHERLOCK HOLMES ***\n\n\n\nProduced by an anonymous Project Gutenberg volunteer and Jose Menendez\n\n\n\ncover\n\n\n\nThe Adventures of Sherlock Holmes\n\n\n\nby Arthur Conan Doyle\n\n\n\nContents\n\n\n   I.     A Scandal in Bohemia\n   II.    The Red-Headed League\n   III.   A Case of Identity\n   IV.    The Boscombe Valley Mystery\n   V.     The Five Orange Pips\n   VI.    The Man wi

In [4]:
# filters = '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t'

## **Define A Tokernizer**

In [5]:
tokernizer = tf.keras.preprocessing.text.Tokenizer()

In [6]:
tokernizer.fit_on_texts([text])

## **Numerical Representation and Word Counts and Other Details**

In [7]:
tokernizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"\\ufeff": 1, "project": 90, "gutenberg\'s": 1, "the": 5715, "adventures": 11, "of": 2770, "sherlock": 101, "holmes": 442, "by": 363, "arthur": 19, "conan": 4, "doyle": 4, "this": 496, "ebook": 11, "is": 1125, "for": 741, "use": 46, "anyone": 29, "anywhere": 4, "at": 772, "no": 325, "cost": 6, "and": 2949, "with": 876, "almost": 20, "restrictions": 2, "whatsoever": 2, "you": 1394, "may": 209, "copy": 14, "it": 1566, "give": 62, "away": 107, "or": 272, "re": 4, "under": 49, "terms": 24, "gutenberg": 99, "license": 18, "included": 4, "online": 4, "www": 10, "net": 2, "title": 3, "author": 1, "release": 1, "date": 11, "november": 1, "29": 1, "2002": 1, "1661": 4, "last": 92, "updated": 2, "20": 2, "2019": 1, "language": 2, "english": 10, "character": 20, "set": 52, "encoding": 1, "utf": 1, "8": 7, "start": 

In [8]:
# Get the word indexes
tokernizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'i': 6,
 '”': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'he': 11,
 'was': 12,
 'you': 13,
 'his': 14,
 'is': 15,
 'my': 16,
 'have': 17,
 'with': 18,
 'as': 19,
 'had': 20,
 'at': 21,
 'which': 22,
 'for': 23,
 'be': 24,
 'not': 25,
 'me': 26,
 'but': 27,
 'from': 28,
 'we': 29,
 'this': 30,
 'said': 31,
 'upon': 32,
 'there': 33,
 'holmes': 34,
 'him': 35,
 'so': 36,
 'her': 37,
 'she': 38,
 'all': 39,
 '’': 40,
 'been': 41,
 'your': 42,
 'on': 43,
 'very': 44,
 'by': 45,
 'one': 46,
 'are': 47,
 '“i': 48,
 'were': 49,
 'an': 50,
 'no': 51,
 'would': 52,
 'out': 53,
 'what': 54,
 'then': 55,
 'up': 56,
 'when': 57,
 'man': 58,
 'could': 59,
 'has': 60,
 'do': 61,
 'into': 62,
 'or': 63,
 'little': 64,
 'will': 65,
 'who': 66,
 'mr': 67,
 'if': 68,
 'some': 69,
 'down': 70,
 'see': 71,
 'now': 72,
 'our': 73,
 'should': 74,
 'may': 75,
 'am': 76,
 'us': 77,
 'over': 78,
 'they': 79,
 'can': 80,
 'more': 81,
 'think': 82,
 'about': 83,
 'mu

In [9]:
input_sequences = []

# Splitting sentenses by using newline character
for sentense in text.split('\n'):
  print(sentense)
  token_list = tokernizer.texts_to_sequences([sentense])[0]  # Convert To Numerical
  print(token_list)
  for i in range(1, len(token_list)):
    sequence = token_list[:i+1]
    input_sequences.append(sequence)

Streaming output truncated to the last 5000 lines.
He was a man of about fifty, tall, portly, and imposing, with a
[11, 12, 5, 58, 4, 83, 955, 950, 3627, 2, 8150, 18, 5]
massive, strongly marked face and a commanding figure. He was dressed
[1800, 1965, 958, 102, 2, 5, 8151, 616, 11, 12, 457]
in a sombre yet rich style, in black frock-coat, shining hat, neat
[8, 5, 2580, 157, 1034, 3201, 8, 250, 1402, 412, 997, 263, 2000]
brown gaiters, and well-cut pearl-grey trousers. Yet his actions were
[733, 2459, 2, 115, 393, 8152, 497, 1520, 157, 14, 2247, 49]
in absurd contrast to the dignity of his dress and features, for he was
[8, 2500, 2097, 3, 1, 2503, 4, 14, 436, 2, 842, 23, 11, 12]
running hard, with occasional little springs, such as a weary man gives
[912, 403, 18, 2638, 64, 8153, 114, 19, 5, 1002, 58, 1397]
who is little accustomed to set any tax upon his legs. As he ran he
[66, 15, 64, 1499, 3, 243, 89, 1458, 32, 14, 1504, 19, 11, 423, 11]
jerked his hands up and down, waggled his hea

In [10]:
input_sequences[:5]

[[145, 4790],
 [145, 4790, 1],
 [145, 4790, 1, 1020],
 [145, 4790, 1, 1020, 4],
 [145, 4790, 1, 1020, 4, 128]]

## **Add padings to set all the input sequences to same length**

In [11]:
# Get maximum sequence length
max_length = max([len(input_sequences) for input_sequences in input_sequences])
max_length

20

In [12]:
# Add padings
input_sequences = tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding="pre")
input_sequences[:5]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,  145, 4790],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,  145, 4790,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,  145, 4790,    1, 1020],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  145, 4790,    1, 1020,    4],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,  145, 4790,    1, 1020,    4,  128]],
      dtype=int32)

In [13]:
input_sequences[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,  145, 4790], dtype=int32)

In [14]:
len(input_sequences[0])

20

## **Feature and label Extraction**

In [15]:
x = input_sequences[:, :-1]  # Feature
y = input_sequences[:, -1]   # Label

In [16]:
# Fetures of 1st record
x[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0, 145], dtype=int32)

In [17]:
# label of the 1st record
y[0]

4790

## **One Hot Encoding**

In [18]:
num_classes = len(tokernizer.word_index) + 1
num_classes

8932

In [19]:
# Encoding
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

## **Model Building**

In [20]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Embedding(num_classes, 100, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(128))
model.add(tf.keras.layers.Dense(num_classes, activation="softmax"))

#compile
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

#summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 19, 100)           893200    
                                                                 
 lstm (LSTM)                 (None, 128)               117248    
                                                                 
 dense (Dense)               (None, 8932)              1152228   
                                                                 
Total params: 2162676 (8.25 MB)
Trainable params: 2162676 (8.25 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
# Train the model
history = model.fit(x, y, epochs=100)

Epoch 1/100
3176/3176 [==============================] - 43s 13ms/step - loss: 6.2879 - accuracy: 0.0749
Epoch 2/100
3176/3176 [==============================] - 25s 8ms/step - loss: 5.5235 - accuracy: 0.1254
Epoch 3/100
3176/3176 [==============================] - 25s 8ms/step - loss: 5.1157 - accuracy: 0.1515
Epoch 4/100
3176/3176 [==============================] - 25s 8ms/step - loss: 4.7858 - accuracy: 0.1719
Epoch 5/100
3176/3176 [==============================] - 24s 8ms/step - loss: 4.4877 - accuracy: 0.1905
Epoch 6/100
3176/3176 [==============================] - 24s 7ms/step - loss: 4.2080 - accuracy: 0.2094
Epoch 7/100
3176/3176 [==============================] - 24s 8ms/step - loss: 3.9439 - accuracy: 0.2334
Epoch 8/100
3176/3176 [==============================] - 24s 7ms/step - loss: 3.6954 - accuracy: 0.2605
Epoch 9/100
3176/3176 [==============================] - 24s 8ms/step - loss: 3.4572 - accuracy: 0.2923
Epoch 10/100
3176/3176 [==============================] - 24s 8

## **Predictions**

In [22]:
input_text = "Sherlock"

In [23]:
token_list = tokernizer.texts_to_sequences([input_text])[0]
token_list

[128]

In [24]:
# Add padding and fix max sequence length
token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding="pre")
token_list

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 128]], dtype=int32)

In [25]:
predicted = np.argmax(model.predict(token_list), axis=-1)
predicted

1/1 [==============================] - 1s 560ms/step


array([34])

In [26]:
for word, index in tokernizer.word_index.items():
  if index == predicted:
    print(word)

holmes


In [28]:
input_text = "They"

for i in range(6):
  token_list = tokernizer.texts_to_sequences([input_text])[0]
  token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length, padding="pre")
  predicted = np.argmax(model.predict(token_list), axis=-1)
  output_word = ""
  for word, index in tokernizer.word_index.items():
    if index == predicted:
      output_word = word
      break
  input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 22ms/step
They were too excited in the chase
